from position import Position

class Error:
    def __init__(self, start: Position, end: Position, message: str) -> None: ...
    def __repr__(self) -> str: ...

class InvalidCharError(Error): ...
class InvalidSyntaxError(Error): ...
class RuntimeError(Error): ...
