from typing import NoReturn, overload

from nodes import BinOpNode, Node, NumberNode, UnaryOpNode
from results import RuntimeResult
from values import Number

class Interpreter:
    @overload
    def visit(self, node: Node) -> Number: ...
    @overload
    def visit(self, node: Node) -> NoReturn: ...
    def no_visit_method(self, node: Node) -> NoReturn: ...
    def visit_numbernode(self, node: NumberNode) -> RuntimeResult: ...
    def visit_binopnode(self, node: BinOpNode) -> Number: ...
    def visit_unaryopnode(self, node: UnaryOpNode) -> Number: ...
