from tokens import Token

class Node:
    def __init__(self, token: Token) -> None: ...
    def __repr__(self) -> str: ...

class NumberNode(Node): ...

class BinOpNode(Node):
    def __init__(self, left_node: Node, op_token: Token, right_node: Node) -> None: ...
    def __repr__(self) -> str: ...

class UnaryOpNode(Node):
    def __init__(self, op_token: Token, node: Node) -> None: ...
    def __repr__(self) -> str: ...
